#98 Change mode added
moevm/phsycho_bot pull request #110
Opened 2023-07-20 15:09 UTC by elizaveta-andreeva

2023-07-20 15:37 UTC, thehighestmath requested changes

2023-07-20 15:37 UTC, thehighestmath commented on bot.py
> +MODE = True
> Выносим MODE в настройки конкретного пользователя, а не всей системы в целом

2023-09-15 11:29 UTC, zmm commented on wrapper.py
> +        update.effective_user.send_message(text=text, reply_markup=reply_markup)
Часть нужной логики из dialog_Wrapper отсутствует в dialog. Нужно ее туда аккуратно перенести, dialog_Wrapper удалить

2023-09-15 11:36 UTC, zmm commented
Общение с ботом застревает на этапе 
"Ты выбрал фокусом этой недели работу с усталостью. Для начала вспомни, какие события или действия наполняют тебя ресурсом, дает прилив энергии и сил?"

2023-09-29 11:54 UTC, thehighestmath commented on bot.py
> +MODE = True
А эта константа точно используется?

2023-10-20 12:13 UTC, merged