#117 Question DB
moevm/phsycho_bot pull request #128
Opened 2023-10-20 12:04 UTC by feyhoa

2023-10-20 12:50 UTC, thehighestmath commented on bot.py
> +        update.effective_user.send_message("Неверно введён id пользователя!")
Точно мы хотим исключение тут обрабатывать? может заиспользуем это? https://pythonz.net/references/named/str.isdigit/

2023-11-11 17:55 UTC, thehighestmath requested changes

2023-11-11 17:55 UTC, thehighestmath commented on db.py
> +            language_code='ru',
зачем так?

2023-11-11 17:55 UTC, thehighestmath commented on questions_db.py
> +        return None
если функция созвращает список вопросов, то если вопросов нет не логичнее возвразщать пустой список?)

2023-11-11 17:55 UTC, thehighestmath commented on bot.py
> +            update.message.reply_text("Не введён id пользователя!")
может сделать
if not user.is_admin:
  return
?
И все остальное подвинуть (уменьшится цикломатическая сложность)

2023-11-11 17:55 UTC, thehighestmath commented on bot.py
> +
зачем?)

2023-11-11 17:55 UTC, thehighestmath commented on db.py
> +def get_user(user_id: int) -> Union[User, None]:
Optional[User]?

2023-11-12 19:44 UTC, feyhoa commented on db.py
> +            language_code='ru',
в rocket chat описал проблему, там можете посмотреть

2024-02-07 08:20 UTC, thehighestmath requested changes

2024-02-07 08:20 UTC, thehighestmath commented on bot.py
> +        print("get_user_initial_reason_flag")
точно принт нужен или остался после дебага?)

2024-02-07 08:20 UTC, thehighestmath commented on bot.py
> +        update.message.reply_text("Произошла ошибка.")
кажется сюда мы попадаем тоько если длина текста равна нулю
не хотим ли мы пользователю об этом сообщить? [ ну чтобы он исправился :) ]
(а то "произошла ошибка" звучит слишком абстрактно)

2024-02-07 08:20 UTC, thehighestmath commented on bot.py
> +        update.message.reply_text("Не введён id пользователя!")
*Пожелание*
Попробуйте так заиспользовать код, кажется что так лучше читаемость (early return https://habr.com/ru/articles/348074/)
Только пришлось вызов функции `set_last_usage(update.effective_user)` поднять повыше, если это что-то сломало, то надо смотреть
```python
def add_admin(update: Update, context: CallbackContext):
    user = init_user(update.effective_user)
    if not user.is_admin:
        return

    if not len(context.args):
        update.message.reply_text("Не введён id пользователя!")
        return

    db_id = context.args[0]
    set_last_usage(update.effective_user)

    if not (db_id.isdigit() and 6 <= len(db_id) <= 10):
        update.message.reply_text("Некорректно введён id пользователя!")
        return

    create_admin(int(db_id))
    update.message.reply_text(f"Выданы права администратора пользователю с id: {db_id}")
```

2024-02-07 08:20 UTC, thehighestmath commented on bot.py
> +    set_last_usage(update.effective_user)
Также советую проверить на работоспособность эту версию кода :)
```python
def get_questions(update: Update, context: CallbackContext):
    user = init_user(update.effective_user)
    if not user.is_admin:
        return

    questions = list_questions()
    count_questions = len(questions)
    pages = (count_questions // 10) + (1 if count_questions % 10 else 0)

    update.message.reply_text(f"Всего страниц: {pages}.")
    set_last_usage(update.effective_user)

    if not pages:
        return

    if len(context.args) and context.args[0].isdigit():
        out_page_number = int(context.args[0])

        if out_page_number > pages:
            out_page_number = 1
    else:
        out_page_number = 1

    page_questions = questions[(out_page_number - 1) * 10: out_page_number * 10 - 1]
    out_questions = '\n\n'.join([dict_to_str_question(elem) for elem in page_questions])
    update.message.reply_text(out_questions)
```

2024-02-07 08:20 UTC, thehighestmath commented on bot.py
> +    pages = (count_questions // 10) + (1 if count_questions % 10 else 0)
а разве округление вверх не поможет?) да и читается лучше :)
```python
import math
math.ceil(count_questions / 10)
```

2024-02-07 08:20 UTC, thehighestmath commented on db.py
> +            user.save()
есть сайд эффект "насильного" присвоения админской роли?
я про то, точно ли проверка на `if not user.is_admin` нужна?

2024-02-07 08:20 UTC, thehighestmath commented on db.py
> +        db_user.save()
```python
def update_info(user) -> None:
    db_user = init_user(user)

    if not db_user:
        return

    db_user.last_name = user.last_name
    db_user.first_name = user.first_name
    db_user.username = user.username
    db_user.is_bot = user.is_bot
    db_user.save()
```

2024-02-07 08:20 UTC, thehighestmath commented on questions_db.py
> +        ).save()
И вопросик
А зачем нам вызывать тогда эту функцию с `text=''`?
```python
def init_question(user: User, text):
    if not text:
        return

    Question(
        user_id=user.id,
        username=user.username,
        text=text,
        answered=False,
        date=datetime.now(),
        select=-1
    ).save()
```

2024-02-07 08:20 UTC, thehighestmath commented on questions_db.py
> +        return None
https://rollbar.com/blog/python-catching-multiple-exceptions/#
```python
except (InvalidId, Question.DoesNotExist):
    return None
```
Вроде должно сработать

2024-02-07 08:20 UTC, thehighestmath commented on questions_db.py
> +        question.save()
```python
def init_answer(question_id, text):
    if not text:
        return

    Answer(
        question_id=question_id,
        text=text,
        date=datetime.now()
    ).save()

    question = get_question(question_id)
    question.answered = True
    question.select = -1
    question.save()
```

2024-02-07 09:36 UTC, feyhoa commented on db.py
> +            user.save()
в моём понимании, лучше, наверное, сделать ещё 1 проверку, чем генерировать запрос в бд для сохранения.
поправьте меня, если я не прав

2024-02-07 09:46 UTC, thehighestmath commented on db.py
> +            user.save()
понял, справедливо
не подумал о генерации запроса в бд

2024-05-31 11:31 UTC, zmm commented on src/databases/questions_db.py
> +    return f'Ответ: {answer.text} \n{answer.date.strftime("%d/%m/%Y, %H:%M:%S")}'
Давайте показывать в Московском времени

2024-05-31 11:33 UTC, zmm commented on src/databases/questions_db.py
> +            f'\nВопрос: {quest_dict["text"]} \n{quest_dict["date"].strftime("%d/%m/%Y, %H:%M:%S")}')
В Московском времени

2024-05-31 11:57 UTC, zmm commented on src/commands/admin_commands.py
> +        send_answer_to_user(selected_question, text)
Я бы вот тут отправлял не в лоб сам текст, а что то в духе: "НЕкоторое время назад вы задавали вопрос .... .Наш агент поддержки нашел ответ: .... "

2024-05-31 12:37 UTC, zmm commented on src/commands/admin_commands.py
> +        update.message.reply_text("Произошла ошибка.")
Нужно чуть подробнее написать -  сейчас не понятно, в чем пользователь ошибся

2024-05-31 12:37 UTC, zmm commented on src/commands/admin_commands.py
> +    answer = get_answer(answer_id)
Я предлагаю вывести и ответ, и вопрос

2024-06-25 13:33 UTC, merged