Add a voice message download
moevm/phsycho_bot pull request #58
Opened 2023-03-08 15:07 UTC by AntonSeredenkov

- Добавил скачивание голосового сообщения и преобразование его из формата .ogg в .wav
- Добавил преобразование аудиофайла в текст. Требует доработки

2023-03-08 20:20 UTC, thehighestmath requested changes

2023-03-08 20:20 UTC, thehighestmath commented on bot.py
> +import json
бахнуть бы optimize imports в pycharm 
> To optimize imports in a file, you can also press Ctrl+Alt+Shift+L , select Optimize imports, and click Run

2023-03-08 20:20 UTC, thehighestmath commented on bot.py
> +    #update.message.reply_text(generated_text)
точно нужны комменты?

2023-03-08 20:20 UTC, thehighestmath commented on bot.py
> +
пустые стоки? +коммент `print(dir(...))`

2023-03-08 20:20 UTC, thehighestmath commented on bot.py
> +
зачем пустые сточки?)

2023-03-08 20:20 UTC, thehighestmath commented on bot.py
> +    ogg_filename = ogg_filename.split('/')[-1]
**enhancement**
я понимаю, что мы в докере и у нас unix пути, но мб юзать всякие os.path / pathlib

2023-03-08 20:20 UTC, thehighestmath commented on bot.py
> +    command = f"ffmpeg -i {ogg_filename} -ar 16000 -ac 1 -ab 256K -f wav {wav_filename}"
имхо, магические переменные (16000, 256К) я работал с ffmpeg чуть-чуть, но так с ходжу понять сложно за что отвечают параметры, +менять значения в переменных будет проще :)

2023-03-08 20:20 UTC, thehighestmath commented on bot.py
> +    _ = subprocess.check_call(command.split())
зачем `_`?

2023-03-10 11:03 UTC, Anya18 commented
Добавьте отправку пользователю голосового сообщения в ответ

2023-03-11 10:52 UTC, Anya18 commented
Также такие вещи как конвертиция файла с аудиозаписью и преобразование аудио в текст нужно вынести в отдельный модуль

2023-03-14 13:55 UTC, merged