#65 Message recognition statistics
moevm/phsycho_bot pull request #69
Opened 2023-03-31 17:17 UTC by AntonSeredenkov

- Улучшено распознавание текста в  аудиосообщении и добавлена дополнительная информация по словам в тексте.
- Реализован класс для работы со словами в тексте.
- Реализован класс для работы с текстом.
- Изменена отправка сообщения. Теперь вместе с исходным текстом отправляется подробная статистика.

2023-03-31 18:29 UTC, thehighestmath requested changes

2023-03-31 18:29 UTC, thehighestmath commented on audio_classes.py
> +class recognized_word:
Pep8 плачет

2023-03-31 18:29 UTC, thehighestmath commented on audio_classes.py
> +    def get_word(self):
Может проперти?

2023-03-31 18:29 UTC, thehighestmath commented on audio_classes.py
> +class recognized_sentence:
Pep8

2023-03-31 19:07 UTC, thehighestmath commented on audio_classes.py
> +class recognized_sentence:
Ok

2023-03-31 19:07 UTC, thehighestmath commented on audio_classes.py
> +class recognized_word:
Ok

2023-03-31 19:40 UTC, thehighestmath commented on audio_classes.py
> +class RecognizedWord:
А датакласс не покатит тут?
+ аттрибуты класса `start,end,conf` не выглядят очень понятными :(

2023-03-31 19:41 UTC, thehighestmath commented on audio_classes.py
> +            answer += f"Слово \"{i.get_word()}\" было сказано в промежутке {i.get_start()} - {i.get_end()} с " \
Time complexity -- O(n^2) 
Можно попробовать лучше :)

2023-03-31 20:15 UTC, AntonSeredenkov commented on audio_classes.py
> +            answer += f"Слово \"{i.get_word()}\" было сказано в промежутке {i.get_start()} - {i.get_end()} с " \
Не понимаю. Почему O(n^2)?

2023-04-01 04:38 UTC, thehighestmath commented on audio_classes.py
> +            answer += f"Слово \"{i.get_word()}\" было сказано в промежутке {i.get_start()} - {i.get_end()} с " \
Строки в питоне неизменяемые
https://ru.stackoverflow.com/questions/607740/%D0%A1%D0%BB%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%B0-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BA-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B5-%D0%B2-%D1%86%D0%B8%D0%BA%D0%BB%D0%B5

2023-04-01 11:04 UTC, thehighestmath commented on audio_classes.py
> +class RecognizedWord:
Ok

2023-04-01 11:05 UTC, thehighestmath approved these changes
Мне нравится

2023-04-05 12:04 UTC, merged