#71 Silero demo
moevm/phsycho_bot pull request #74
Opened 2023-05-16 09:04 UTC by zweig228

2023-05-16 09:17 UTC, zweig228 commented
Также был оптимизирован Dockerfile

2023-05-23 08:30 UTC, zmm requested changes

2023-05-24 17:07 UTC, Roman1621 commented on silero_demo/silero_test.py
> +    audio = model.apply_tts(text=example_text,
Получилось сделать, чтобы он из текстового сообщения брал фразу для ответа. Для голосового в пример придётся ещё добавлять расшифровку сообщения. Сделать это в рамках основного бота несложно, но в примере потребует добавление ещё и vosk`а

2023-05-24 17:08 UTC, Roman1621 commented on silero_demo/docker-compose.yml
> +    env_file: .env
Для подгрузки токена и для подгрузки режима работы. Удалили config.py, ибо он не нужен

2023-05-26 09:59 UTC, merged